name: OneStopShop
main: lee.code.onestopshop.OneStopShop
version: ${project.version}
api-version: 1.13
author: Lee
softdepend: [Vault]
commands:
  shop:
    description: Opens shop menu.
    permission: oss.shop.use